apiVersion: apps/v1
kind: Deployment
metadata:
  name: exercise
  labels:
    app: exercise
spec:
  replicas: 1
  template:
    metadata:
      name: exercise
      labels:
        app: exercise
    spec:
      containers:
        - name: exercise
          image: go-scaffold-exercise:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
      restartPolicy: Always
  selector:
    matchLabels:
      app: exercise
